### ISSUE TITLE
On what basis does the docker blueprint gain the rights to localhost:9000?

### ISSUE THREAD

**Issue by kaosmaja** [canonical/multipass-blueprints#42]
I cannot see anything special like bridging ports to the host machine, so how come portainer shows up on localhost? Usually you'd have to use the VM's IP.

**Comment by townsend2010** [comment]
Hi @kaosmaja!

Could you please provide a few more details of your Multipass setup such as the output of `multipass get local.driver` and the host OS you are using?  You *might* be using Virtualbox, but it's not clear to me at this time.  Thanks!

**Comment by kaosmaja** [comment]
The output gives me QEMU and I'm using multipass 1.13.1 on Ubuntu 22.04 LTS. The behavior I'm seeing comes from a fresh `multipass launch docker`, and I have not added any blueprint sources. To be clear, I'm fairly sure I don't have VBox on this machine.

**Comment by townsend2010** [comment]
Ok, you are definitely not using VBox.  I launched the `docker` Blueprint on my 22.04 machine and `localhost:9000` is not reachable and I have to use the Multipass instance's IP address. Do you happen to have Docker/Portainer installed and running directly on your host?

**Comment by kaosmaja** [comment]
I don't think I have portainer but I do have docker installed but not running. Do you think it uses the default docker network to achieve this?

**Comment by townsend2010** [comment]
Hi @kaosmaja,

I have docker running on my machine and `localhost:9000` does not work (as expected).  Aside from doing some manual port forwarding, the only way I can get that to work is to install and run Portainer on my host.  I really have no idea why this behavior is happening for you.  The Docker Blueprint is certainly not doing anything itself to make this happen.

**Comment by kaosmaja** [comment]
Thanks for testing! This has not persisted between restarts either, so maybe it's just a local thing after I messed around too much.
